# Install script for directory: /Users/epsund/Downloads/aws-sdk-cpp-master

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/AWSSDK" TYPE FILE FILES "/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/AWSSDK/AWSSDKConfigVersion.cmake")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/AWSSDK" TYPE FILE FILES "/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/AWSSDK/platformDeps.cmake")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/AWSSDK" TYPE DIRECTORY FILES "/Users/epsund/Downloads/aws-sdk-cpp-master/cmake/")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-acm/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-apigateway/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-application-autoscaling/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-appstream/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-athena/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-autoscaling/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-batch/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-budgets/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-clouddirectory/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cloudformation/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cloudfront/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cloudhsm/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cloudsearch/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cloudsearchdomain/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cloudtrail/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-codebuild/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-codecommit/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-codedeploy/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-codepipeline/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-codestar/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cognito-identity/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cognito-idp/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cognito-sync/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-config/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cur/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-datapipeline/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-devicefarm/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-directconnect/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-dms/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-ds/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-dynamodb/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-dynamodbstreams/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-ec2/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-ecr/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-ecs/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elasticache/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elasticbeanstalk/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elasticfilesystem/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elasticloadbalancing/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elasticloadbalancingv2/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elasticmapreduce/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-elastictranscoder/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-email/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-es/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-events/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-firehose/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-gamelift/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-glacier/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-greengrass/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-health/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-iam/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-importexport/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-inspector/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-iot/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-iot-data/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-kinesis/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-kinesisanalytics/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-kms/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-lambda/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-lex/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-lex-models/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-lightsail/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-logs/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-machinelearning/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-marketplacecommerceanalytics/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-meteringmarketplace/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-mobileanalytics/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-monitoring/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-mturk-requester/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-opsworks/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-opsworkscm/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-organizations/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-polly/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-pinpoint/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-rds/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-redshift/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-rekognition/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-resourcegroupstaggingapi/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-route53/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-route53domains/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-s3/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-sdb/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-servicecatalog/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-shield/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-sms/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-snowball/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-sns/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-sqs/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-ssm/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-states/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-storagegateway/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-sts/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-support/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-swf/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-waf/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-waf-regional/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-workspaces/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-workdocs/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-xray/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-core/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-access-management/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-identity-management/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-queues/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-transfer/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-s3-encryption/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-text-to-speech/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/testing-resources/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-cognitoidentity-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-dynamodb-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-ec2-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-lambda-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-s3-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-sqs-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-core-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-identity-management-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-transfer-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-s3-encryption-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-s3-encryption-integration-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-text-to-speech-tests/cmake_install.cmake")
  include("/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/aws-cpp-sdk-polly-sample/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/epsund/angelhacks/moodhub/moodhub/aws-sdk/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
